### PR TITLE
Fix hello world verification

### PR DESCRIPTION
**Pull request by tanem**
Check for correct file and use success message.

### CODE REVIEW

**Comment by benwiley4000** [comment]
Please merge. Thanks!

**Comment by gyaresu** [comment]
I'm confused. Master here is showing as 1.3.4 but I've just gotten the npm module which is 1.3.5 and it's still failing on `index.js`.

Any idea how this is happening?

**Comment by danfinlay** [comment]
I don't have npm deploy powers, I have merge powers. My guess is that @maxogden did a hot-patch in the past up to 1.3.5, and that's on npm. Your fix is on master, and is waiting for him to version-bump and publish to npm.

Hey Max, I think @gyaresu would like the latest master pushed to npm.

**Comment by kvsm** [comment]
Would be nice, I just tripped over the same thing.

**Pull request merged**
